-- File: overflow_detector.vhd
-- Generated by MyHDL 0.11.49
-- Date: Sat Dec 21 01:04:31 2024


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_011.all;

entity overflow_detector is
    port (
        a: in unsigned(0 downto 0);
        b: in unsigned(0 downto 0);
        sum: in unsigned(0 downto 0);
        Overflow: out unsigned(0 downto 0)
    );
end entity overflow_detector;


architecture MyHDL of overflow_detector is




begin





Overflow <= (((a and b) and (not sum)) or (((not a) and (not b)) and sum));

end architecture MyHDL;
